services:
  frontend:
    build: ../services/gateway
    ports:
      - "3000:3000"
    depends_on:
      - auth
      - users
      - orders
    networks:
      - frontend_net
      - backend_net

  auth:
    build: ../services/auth
    ports:
      - "4001:4000"
    secrets:
      - jwt_secret
    environment:
      JWT_SECRET_FILE: /run/secrets/jwt_secret
    networks:
      - frontend_net
      - backend_net

  users:
    build: ../services/users
    ports:
      - "4002:4000"
    environment:
      DATABASE_URL: postgresql://user:$(cat /run/secrets/db_password)@db:5432/usersdb
    secrets:
      - db_password
    networks:
      - frontend_net
      - backend_net

  orders:
    build: ../services/orders
    ports:
      - "4003:4000"
    environment:
      DATABASE_URL: postgresql://user:$(cat /run/secrets/db_password)@db:5432/ordersdb
    secrets:
      - db_password
    networks:
      - backend_net


  gateway:
    build: ../services/gateway
    ports:
      - "80:80"
    depends_on:
      - auth
      - users
      - orders
    networks:
      - frontend_net


  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend_net
